services:
  flask:
    build: .
    command: flask run --host=0.0.0.0 --port=5000 --debug
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  tailwind:
    build: .
    command: npx tailwindcss -i ./static/src/css/styles.css -o ./static/dist/css/output.css --watch
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true

  webpack:
    build: .
    command: npx webpack --watch
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
