# Use an official Node.js image as the base image
FROM node:lts

# Set the working directory
WORKDIR /usr/src/app

# Copy project files
COPY . .

# Install Node.js dependencies
RUN npm install

# Install Tailwind CSS globally
RUN npm install -g tailwindcss

# Run Tailwind CSS
CMD ["npx", "tailwindcss", "-i", "./static/src/css/styles.css", "-o", "./static/dist/css/output.css", "--watch"]
